name: Generate Coverage Badge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run tests and collect coverage
        run: |
          pytest --cov=pyTGA --cov-report=xml
      - name: Generate coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: coverage-badge.svg
      - name: Commit and push badge
        uses: EndBug/add-and-commit@v9
        with:
          add: 'coverage-badge.svg'
          message: 'chore: update coverage badge [skip ci]'
          default_author: github_actions
